name : 'My First GitHub Actions Workflow' 

on: push 
# on은 깃허브 액션이 작동하게 하는 trigger 같은 것 

env:
  WORKFLOW_LEVEL: 'This value comes fom the workflow level'

jobs: 
  fist-job: 
    name: 'first Job'

    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest','macos-latest']
        nodejs : ['14.x', '16.x']

    runs-on : ${{ matrix.os }}
    # 즉 first job이 각 os에서 3번 돈다! 
  
    steps:
      - name: 'Setup node.js version'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: 'Check node.js version on ${{ matrix.os }}'
        shell: bash
        run: |
          echo "nodejs version: $(node --version)"

    

## 즉 총 6번 돈다 os버전 * nodejs 버전 == 6

                         

