name: 'My First GitHub Actions'

on: push

env:
  PRESET_VALUE: "This is the preset value"

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variable 1
      shell: bash
      run: |
        echo "STEPSET_VALUE_1='This is the value 1 set in the step'" >> $GITHUB_ENV

    - name: Set environment variable 2
      shell: pwsh
      run: |
        echo "STEPSET_VALUE_2='This is the value 2 set in the step'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Check environment variables
      shell: bash
      run: |
        echo "preset value: ${{ env.PRESET_VALUE }}"
        echo "stepset value 1: ${{ env.STEPSET_VALUE_1 }}"
        echo "stepset value 2: ${{ env.STEPSET_VALUE_2 }}"