name : 'My First GitHub Actions Workflow' 

on: push 
# on은 깃허브 액션이 작동하게 하는 trigger 같은 것 

env:
  WORKFLOW_LEVEL: 'This value comes fom the workflow level'

jobs: 
  fist-job: 
    name: 'first Job'
    runs-on : 'ubuntu-latest'
    # ['windows-latest', 'ubuntu-latest','macos-latest'] # 어떤 운영체제에서 실행시킬 것인지 설정!! ㅣ건 3개의 OSd에서 동시에 실행 가능! 
  
    steps:
    - name: 'Set environment variable 1'
      shell: bash
      run: |
        echo "STEP_1 ='This value comes from the step 1'" >> $GITHUB_ENV

    - name: 'Set environment variable 2'
      shell: pwsh
      run : |
        echo "STEP_2 ='This value comes from the step 2'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name : 'Get environment variables'
      shell: bash
      run: |
        echo "WORKFLOW: ${{ env.WORKFLOW_LEVEL }}"
        echo "STEP 1: ${{ env.STEP_1 }}"
        echo "STEP 2: ${{ env.STEP_2 }}"

# 환경변수 표현! 
#power shell은 변수 가져ㅗ는 방식이 다르지? bash랑 다름 
# github action은 ${{}} 이렇게!! 
# GITHUB_ENV에 "STEP1~"을 저장해라! 
