name : 'My First GitHub Actions Workflow' 

on: push 

env:
  WORKFLOW_LEVEL: 'This value comes fom the workflow level'

jobs: 
  fist-job: 
    name: 'first Job'

    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest','macos-latest']

    runs-on : ${{ matrix.os }}
    # 즉 first job이 각 os에서 총 3번 돈다! dd
  
    steps:
    - name: 'Say Hello on ${{ matrix.os }}'
      shell: bash
      run: |
        echo "Hello from ${{ matrix.os }}"