name : 'My First GitHub Actions Workflow' 

on: push 
# on은 깃허브 액션이 작동하게 하는 trigger 같은 것 

env:
  WORKFLOW_LEVEL: 'This value comes fom the workflow level'

jobs: 
  fist-job: 
    name: 'first Job'

    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest','macos-latest']

    runs-on : ${{ matrix.os }}
    # 즉 first job이 각 os에서 3번 돈다! 
  
    steps:
    - name: 'Say Hello on ${{ matrix.os }}'
      shell: bash
      run: |
        echo "Hello from ${{ matrix.os }}"


                         
                        
# 변수값 지정 후 
# output 변수 이름을 step1 이라 하고 그 STEP1에 할당! 
# set-ouput이라는게 다른 step에서 참조해줄 수 있게 함
# add-mask하면 민감 정보를 ***이렇게 표시하게 함! -> Secret 이용할 수도 있음!! 
